# Generated by Django 5.2.7 on 2025-11-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
